version: '3.8'
services:
  app:
    build: ./app
    command: sleep infinity
    volumes:
      - ./app:/app
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: 2kzOoBVNwNAy2BJqOSlTiUFCiRZboBWpV6Q4RfCTEefDwmE815aeHRkeDhG5Zv6r
      HASURA_GRAPHQL_GRAPHQL_URL: https://ethical-doberman-9365.ddn.hasura.app/graphql
    ports:
    - "3001:3000"
    # - "9695:9695"